name: CI

on: push

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
      fail-fast: false
    runs-on: ${{ matrix.os }}
    env:
      CI_OS_NAME: ${{ matrix.os }}
    steps:
      - run: '@echo %APPDATA%'
        if: matrix.os == 'windows-latest'
        shell: cmd
      - uses: actions/checkout@v3

      # lix
      - uses: lix-pm/setup-lix@master
        with:
          lix-version: 15.12.0


      # run target test:
      - run: lix install gh:nqnstudios/lime#lix-workaround
        if: matrix.os == 'windows-latest'
      - run: lix download
      - run: ls "C:/Users/runneradmin/AppData/Roaming/haxe/haxe_libraries"
        if: matrix.os == 'windows-latest'
      - run: lix run lime
