name: CI

on: push

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
      fail-fast: false
    runs-on: ${{ matrix.os }}
    env:
      CI_OS_NAME: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      # lix
      - uses: lix-pm/setup-lix@master
        with:
          lix-version: 15.12.0
      
      # run target test:
      - run: lix download
      - run: lix run lime
