name: CI

on: push

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
      fail-fast: false
    runs-on: ${{ matrix.os }}
    env:
      CI_OS_NAME: ${{ matrix.os }}
      LIME_PATH: 
    steps:
      - uses: actions/checkout@v3

      # lix
      - uses: lix-pm/setup-lix@master
        with:
          lix-version: 15.12.0

      - run: echo "LIME_PATH=/Users/runner/haxe/haxe_libraries/lime/8.0.1/github/155c498d46fb84c3027e4594b6b3c42342050f04" >> $GITHUB_ENV
        if: matrix.os == 'macos-latest'
      - run: echo "LIME_PATH=/c/Users/runneradmin/appdata/roaming/haxe/haxe_libraries/lime/8.0.1/github/155c498d46fb84c3027e4594b6b3c42342050f04" >> $GITHUB_ENV
        if: matrix.os == 'windows-latest'
      - run: echo "LIME_PATH=$HOME/haxe/haxe_libraries/lime/8.0.1/github/155c498d46fb84c3027e4594b6b3c42342050f04" >> $GITHUB_ENV
        if: matrix.os == 'ubuntu-latest'

      # run target test:
      - run: lix download
      - run: lix run lime
