name: CI

on: push

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
      fail-fast: false
    runs-on: ${{ matrix.os }}
    env:
      CI_OS_NAME: ${{ matrix.os }}
      LIME_PATH: /Users/runner/haxe/haxe_libraries/lime/8.0.1/github/98a02fb5bf76ecf41a2d64d1d5e618a9caf89afc
    steps:
      - uses: actions/checkout@v3

      # lix
      - uses: lix-pm/setup-lix@master
        with:
          lix-version: 15.12.0
      
      # run target test:
      - run: lix download
      - run: lix run lime
