name: CI

on: push

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
      fail-fast: false
    runs-on: ${{ matrix.os }}
    env:
      CI_OS_NAME: ${{ matrix.os }}
      LIME_PATH: /Users/runner/haxe/haxe_libraries/lime/8.0.1/github/c29b00a56e0c9bb425e6d9b275d61f7017e6dd45
    steps:
      - uses: actions/checkout@v3

      # lix
      - uses: lix-pm/setup-lix@master
        with:
          lix-version: 15.12.0
      
      # run target test:
      - run: lix download
      - run: lix install haxe 4.2.5
      - run: lix use haxe 4.2.5
      - run: lix run lime
      - run: lix use haxe 4.3.1
